version: "3.7"

networks:
  frontend:
  backend:

volumes:
  percona:
  redis:

services:
  workspace:
    container_name: {{APP_NAME}}-dev-workspace
    build:
      context: ./docker/workspace
      args:
        APP_DEBUG: "${APP_DEBUG}"
    command: "bash /home/root/docker-entrypoint.sh"
    tty: true
    volumes:
      - .:/var/www:cached
    networks:
      - frontend
      - backend
    environment:
      APP_KEY: "${APP_KEY}"
      APP_ENV: "${APP_ENV}"
      DB_HOST: "${DB_HOST}"
      JWT_SECRET: "${JWT_SECRET}"
      ROOT_PASSWORD: "${PERCONA_ROOT_PASSWORD}"
      PACKAGIST_URL: "${PACKAGIST_URL}"
      PHP_OPCACHE_ENABLE: 0
      PHP_OPCACHE_REVALIDATE_FREQ: 0
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 0
      PHP_OPCACHE_MEMORY_CONSUMPTION: 192
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_HOST: "host.docker.internal"
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_PORT: 9001
      PHP_XDEBUG_IDE_KEY: "VSCODE"
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_ENABLE: 1
      PHP_XDEBUG_PROFILER_ENABLE: 0
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: "/var/www/xdebug_log/xdebug_docker.log"

  api:
    container_name: {{APP_NAME}}-dev-api
    build: ./docker/nginx
    volumes:
      - .:/var/www:cached
      - ./docker/nginx/sites/:/etc/nginx/sites-available
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  php-fpm:
    container_name: {{APP_NAME}}-dev-php-fpm
    build:
      context: ./docker/php-fpm
      args:
        APP_DEBUG: "${APP_DEBUG}"
    expose:
      - 9000
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www:cached
    networks:
      - backend
    environment:
      PHP_OPCACHE_ENABLE: 0
      PHP_OPCACHE_REVALIDATE_FREQ: 0
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 0
      PHP_OPCACHE_MEMORY_CONSUMPTION: 192
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_HOST: "host.docker.internal"
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_PORT: 9001
      PHP_XDEBUG_IDE_KEY: "VSCODE"
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_ENABLE: 1
      PHP_XDEBUG_PROFILER_ENABLE: 0
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: "/var/www/xdebug_log/xdebug_docker.log"
      PHP_XDEBUG_PROFILE_ENABLE_TRIGGER: 1

  laravel-horizon:
    container_name: {{APP_NAME}}-dev-queues
    build:
      context: ./docker/laravel-horizon
      args:
        APP_DEBUG: "${APP_DEBUG}"
    volumes:
      - .:/var/www:cached
      - ./docker/laravel-horizon/supervisord.d:/etc/supervisord.d
    networks:
      - backend
    environment:
      PHP_OPCACHE_ENABLE: 0
      PHP_OPCACHE_REVALIDATE_FREQ: 0
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 0
      PHP_OPCACHE_MEMORY_CONSUMPTION: 192
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_HOST: "host.docker.internal"
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_PORT: 9001
      PHP_XDEBUG_IDE_KEY: "VSCODE"
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_ENABLE: 1
      PHP_XDEBUG_PROFILER_ENABLE: 0
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: "/var/www/xdebug_log/xdebug_docker.log"
      PHP_XDEBUG_PROFILE_ENABLE_TRIGGER: 1

  percona:
    container_name: {{APP_NAME}}-dev-percona
    build:
      context: ./docker/percona
      args:
        DB_USERNAME: "${DB_USERNAME}"
        DB_PASSWORD: "${DB_PASSWORD}"
        DB_DATABASE: "${DB_DATABASE}"
    volumes:
      - percona:/var/lib/mysql
    networks:
      - backend
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${PERCONA_ROOT_PASSWORD}"

  redis:
    container_name: {{APP_NAME}}-dev-redis
    build:
      context: ./docker/redis
      args:
        REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - redis:/data
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog:latest
    container_name: {{APP_NAME}}-dev-mailhog
    ports:
      - 127.0.0.1:1025:1025
      - 127.0.0.1:8025:8025
    networks:
      - backend
